### ISSUE TITLE
[REQUEST] Add option for silencing deew completely/minimal terminal output

### ISSUE THREAD

**Issue by george-avn** [pcroland/deew#42]
When using deew in a limited functionallity terminal enviroment, the program fails to execute because rich cannot render to the terminal, my suggestion is to add an argument that completly silences terminal output (or at least keeps it free of external python dependencies as a very basic version with no progress bar or styling"

Command used
deew.exe -i "inputdir" -b 256 -f ddp -np -o "outputdir"
```
Traceback (most recent call last):
  File "__main__.py", line 6, in <module>
  File "deew\__main__.py", line 551, in main
  File "rich\__init__.py", line 73, in print
  File "rich\console.py", line 1646, in print
  File "rich\console.py", line 848, in __exit__
  File "rich\console.py", line 806, in _exit_buffer
  File "rich\console.py", line 1999, in _check_buffer
  File "rich\_windows_renderer.py", line 17, in legacy_windows_render
  File "rich\_win32_console.py", line 442, in write_styled
  File "rich\_win32_console.py", line 403, in write_text
  File "encodings\cp1252.py", line 19, in encode
UnicodeEncodeError: 'charmap' codec can't encode characters in position 1-5: character maps to <undefined>
[15076] Failed to execute script '__main__' due to unhandled exception!

```

**Comment by george-avn** [comment]
referenced at #43
