### ISSUE TITLE
[REQUEST] Add arg for simple console output 

### ISSUE THREAD

**Issue by xEsteem** [pcroland/deew#48]
Might not be possible, but i've found that some applications that run commandline apps are unable to run deew due to the stdout console output format.

Would it be possible to add a basic mode arg that just list things in plain old console messages rather than the nice formatted console messages which we love to see when running manually?

**Comment by pcroland** [comment]
The output shouldn't cause problems, what are you trying to integrate deew into?

**Comment by xEsteem** [comment]
Staxrip https://github.com/staxrip/staxrip
If you call DEEW through the commandline on staxrip you get an error about the output
I did add an issue a while ago about it, but the repo isnt actively developed (https://github.com/staxrip/staxrip/issues/961)

```
Error Audio Encoding: Command Line (v2.13.0)

-------------------- Audio Encoding: Command Line --------------------

"C:\Program Files\Deew\deew.exe" -i "ID1 English.dtshd" -b 640 -f dd

Traceback (most recent call last):
  File "__main__.py", line 6, in <module>
  File "deew\__main__.py", line 552, in main
  File "rich\__init__.py", line 74, in print
  File "rich\console.py", line 1667, in print
  File "rich\console.py", line 869, in __exit__
  File "rich\console.py", line 827, in _exit_buffer
  File "rich\console.py", line 2024, in _check_buffer
  File "rich\_windows_renderer.py", line 17, in legacy_windows_render
  File "rich\_win32_console.py", line 442, in write_styled
  File "rich\_win32_console.py", line 403, in write_text
  File "encodings\cp1252.py", line 19, in encode
UnicodeEncodeError: 'charmap' codec can't encode characters in position 1-5: character maps to <undefined>
[34264] Failed to execute script '__main__' due to unhandled exception!


   at StaxRip.Proc.Start() in D:\Code\Github\staxrip\staxrip\Source\General\Proc.vb:line 361
   at StaxRip.BatchAudioProfile.Encode() in D:\Code\Github\staxrip\staxrip\Source\General\AudioProfile.vb:line 452
```
